INSERT INTO public.drinks (name,description,image_url,created_at,updated_at,alcohol_level,distilled,temperature,base_ingredient,origin,ibu,drinkware,rating_avg) VALUES
('Caipirinha','Cachaça, also known as caninha, or any one of a multitude of traditional names, is Brazil''s most common distilled alcoholic beverage. Although both rum and cachaça are made from sugarcane-derived products, in cachaça the alcohol results from the fermentation of fresh sugarcane juice that is then distilled, while rum is usually made from refinery by-products such as molasses.','https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/15-09-26-RalfR-WLC-0048.jpg/220px-15-09-26-RalfR-WLC-0048.jpg','2018-07-22 18:50:13.443','2018-07-22 18:50:13.443',35,true,4,'cachaca','Brazil',4,'Old Fashioned Glass',4.85)
,('Brumble','The Bramble is a cocktail created by Dick Bradsell in 1980s London, England. Best described as a spring cocktail, the Bramble brings together dry gin, lemon juice, sugar syrup, crème de mûre, and crushed ice. Bradsell also suggests finishing off the cocktail with some fresh red fruits (such as blackberries, cranberries) and a slice of lemon.','https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Bramble_Cocktail1.jpg/220px-Bramble_Cocktail1.jpg','2018-07-22 18:50:13.446','2018-07-22 18:50:13.446',35,true,3,'gin','London',2,'Old Fashioned Glass',4.25)
,('Aviation','The Aviation is a classic cocktail made with gin, maraschino liqueur, crème de violette, and lemon juice. Some recipes omit the crème de violette. It is served straight up, in a cocktail glass.','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Aviation_Cocktail.jpg/220px-Aviation_Cocktail.jpg','2018-07-22 18:50:13.449','2018-07-22 18:50:13.449',40,true,2,'gin','New York',7,'Cocktail Glass',4.34)
,('Bacardi','The Bacardi Cocktail was originally the same as the Daiquiri, containing rum, lime juice, and sugar; The Grenadine version of the Bacardi Cocktail originated in the US, while the original non-red Bacardi company recipe originated from Cuba.','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Bacardi_cocktail.jpg/220px-Bacardi_cocktail.jpg','2018-07-22 18:50:13.451','2018-07-22 18:50:13.451',28,true,2,'rum','New York',5,'Cocktail Glass',3.88)
,('Daiquiri','Daiquiri is a family of cocktails whose main ingredients are rum, citrus juice (typically lime juice), and sugar or other sweetener. The daiquiri is one of the six basic drinks listed in David A. Embury''s classic The Fine Art of Mixing Drinks. In the book, he also suggests some variations.','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Classic_Daiquiri_in_Cocktail_Glass.jpg/220px-Classic_Daiquiri_in_Cocktail_Glass.jpg','2018-07-22 18:50:13.454','2018-07-22 18:50:13.454',25,true,2,'rum','Cuba',0,'Cocktail Glass',4.4)
,('Mojito','Traditionally, a mojito is a cocktail that consists of five ingredients: white rum, sugar (traditionally sugar cane juice), lime juice, soda water, and mint. The original Cuban recipe uses spearmint or yerba buena, a mint variety very popular on the island.[citation needed] Its combination of sweetness, citrus, and mint flavors is intended to complement the rum, and has made the mojito a popular summer drink','https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/15-09-26-RalfR-WLC-0067.jpg/220px-15-09-26-RalfR-WLC-0067.jpg','2018-07-22 18:50:13.458','2018-07-22 18:50:13.458',10,true,2,'rum','Cuba',9,'Collins Glass',4.9)
,('Sake Bomb','The sake bomb or sake bomber is a beer cocktail made by pouring sake into a shot glass and dropping it into a glass of beer. It should be drunk immediately, and works best with warm sake.','https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Sake_bomb_-_man_pounds_table_with_fist.jpg/220px-Sake_bomb_-_man_pounds_table_with_fist.jpg','2018-07-22 18:50:13.462','2018-07-22 18:50:13.462',60,false,1,'sake','Japan',3,'Shot Glass',4.0)
,('Margarita','A Margarita is a cocktail consisting of tequila, triple sec, and lime juice often served with salt on the rim of the glass. The drink is served shaken with ice (on the rocks), blended with ice (frozen Margarita), or without ice (straight up).','https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/MargaritaReal.jpg/220px-MargaritaReal.jpg','2018-07-22 18:50:13.466','2018-07-22 18:50:13.466',25,true,3,'tequila','Mexico',6,'Margarita Glass',4.8)
,('Tequila Sunrise','The Tequila Sunrise is a cocktail made of tequila, orange juice, and grenadine syrup and served unmixed in a tall glass. The modern drink originates from Sausalito in the early 1970s, after an earlier one created in the 1930s in Phoenix, near Scottsdale. The cocktail is named for its appearance when served, with gradations of color resembling a sunrise.','https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Tequila_Sunrise_garnished_with_orange_and_cherry_-_Evan_Swigart.jpg/220px-Tequila_Sunrise_garnished_with_orange_and_cherry_-_Evan_Swigart.jpg','2018-07-22 18:50:13.470','2018-07-22 18:50:13.470',30,true,3,'tequila','California',1,'Collins Glass',4.65)
,('Bloody Mary','A Bloody Mary is a cocktail containing vodka, tomato juice, and combinations of other spices and flavorings including Worcestershire sauce, hot sauce, piri piri sauce, garlic and herb sauce, beef consommé or bouillon, horseradish, celery, olives, salt, black pepper, lemon juice, lime juice and/or celery salt.','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Bloody_Mary_Coctail_with_celery_stalk_-_Evan_Swigart.jpg/220px-Bloody_Mary_Coctail_with_celery_stalk_-_Evan_Swigart.jpg','2018-07-22 18:50:13.473','2018-07-22 18:50:13.473',38,true,3,'vodka','New York',2,'Highball Glass',4.45)
;
INSERT INTO public.drinks (name,description,image_url,created_at,updated_at,alcohol_level,distilled,temperature,base_ingredient,origin,ibu,drinkware,rating_avg) VALUES
('Cosmopolitan','A cosmopolitan, or informally a cosmo, is a cocktail made with vodka, triple sec, cranberry juice, and freshly squeezed or sweetened lime juice.','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Cosmopolitan_%285076906532%29.jpg/220px-Cosmopolitan_%285076906532%29.jpg','2018-07-22 18:50:13.477','2018-07-22 18:50:13.477',26,true,3,'vodka','New York',4,'Cocktail Glass',4.72)
,('Moscow Mule','Moscow mule is a cocktail made with vodka, spicy ginger beer, and lime juice, garnished with a slice or wedge of lime. It is a type of buck and therefore sometimes known as a vodka buck. The Moscow mule is popularly served in a copper mug. Public health advisories recommend the mugs be plated with nickel or stainless steel on the inside and the lip.','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Moscow_Mule_at_Rye%2C_San_Francisco.jpg/220px-Moscow_Mule_at_Rye%2C_San_Francisco.jpg','2018-07-22 18:50:13.481','2018-07-22 18:50:13.481',32,true,4,'vodka','Los Angeles',2,'Copper Mug',4.99)
,('Sex on the Beach','A Sex on the Beach is a cocktail containing vodka, peach schnapps, orange juice and cranberry juice. The cocktail is usually consumed during summer months. It is considered an IBA Official Cocktail. There are several stories claiming to describe the origin of the Sex on the Beach. One claims that the cocktail originated in Florida, USA in the spring of 1987 coinciding with the introduction of peach schnapps.','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sex_On_The_Beach.jpg/220px-Sex_On_The_Beach.jpg','2018-07-22 18:50:13.484','2018-07-22 18:50:13.484',20,true,3,'vodka','Florida',1,'Highball Glass',4.22)
,('Irish Coffe','Irish coffee (Irish: caife Gailege) is a cocktail consisting of hot coffee, Irish whiskey, and sugar (some recipes specify that brown sugar should be used), stirred, and topped with thick cream. The coffee is drunk through the cream. The original recipe explicitly uses cream that has not been whipped, although drinks made with whipped cream are often sold as ''Irish coffee''.','https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Irish_coffee_glass.jpg/220px-Irish_coffee_glass.jpg','2018-07-22 18:50:13.487','2018-07-22 18:50:13.487',47,true,0,'whiskey','Irish',10,'Irish Coffe Mug',4.57)
,('Manhattan','A Manhattan is a cocktail made with whiskey, sweet vermouth and bitters. While rye is the traditional whiskey of choice, other commonly used whiskeys include Canadian whisky, bourbon, blended whiskey and Tennessee whiskey. The cocktail is usually stirred then strained into a cocktail glass and garnished with a Maraschino cherry.','https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Manhattan_Cocktail2.jpg/220px-Manhattan_Cocktail2.jpg','2018-07-22 18:50:13.490','2018-07-22 18:50:13.490',40,true,2,'whiskey','New York',5,'Cocktail Glass',4.39)
,('Sazerac','The Sazerac is a local New Orleans variation of a cognac or whiskey cocktail, named for the Sazerac de Forge et Fils brand of cognac brandy that served as its original main ingredient.','https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/SazeracRooseveltNOLA1July2009.JPG/220px-SazeracRooseveltNOLA1July2009.JPG','2018-07-22 18:50:13.492','2018-07-22 18:50:13.492',50,true,2,'whiskey','New Orleans',8,'Old Fashioned Glass',3.99)
,('Bellini','The Bellini consists of puréed white peaches and Prosecco, an Italian sparkling wine. Marinating fresh peaches in wine is an Italian tradition. The original recipe was made with a bit of raspberry or cherry juice to give the drink a pink glow. Due, in part, to the limited availability of both white peaches and Prosecco, several variations exist.','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Bellini_Cipriani%2C_Macaroni_Grill%2C_Dunwoody_GA.jpg/220px-Bellini_Cipriani%2C_Macaroni_Grill%2C_Dunwoody_GA.jpg','2018-07-22 18:50:13.499','2018-07-22 18:50:13.499',15,false,2,'wine','Italy',3,'Champagne Flute',4.82)
,('Grasshopper','A grasshopper is a sweet, mint-flavored, after-dinner drink. The name of the drink derives from its green color, which comes from crème de menthe. The drink reputedly originated at Tujague''s, a bar in the French Quarter of New Orleans, Louisiana, and was invented by its owner, Philip Guichet. The drink gained popularity during the 1950s and 1960s throughout the American South.','https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Grasshopper_cocktail.jpg/220px-Grasshopper_cocktail.jpg','2018-07-22 18:50:13.509','2018-07-22 18:50:13.509',18,false,2,'liqueur','New Orleans',5,'Cocktail Glass',4.44)
,('Americano','The Americano is an IBA Official Cocktail[1] composed of Campari, sweet vermouth, and club soda. The cocktail was first served in creator Gaspare Campari''s bar, Caffè Campari, in the 1860s. It was originally known as the ''Milano-Torino'' because of its ingredients: Campari, the bitter liqueur, is from Milan (Milano) and Punt e Mes, the vermouth, is from Turin (Torino).','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Americano_cocktail_at_Nightwood_Restaurant.jpg/220px-Americano_cocktail_at_Nightwood_Restaurant.jpg','2018-07-22 18:50:13.517','2018-07-22 18:50:13.517',22,false,3,'liqueur','Italy',3,'Old Fashioned Glass',3.84)
,('Snakebite','A snakebite is an alcoholic drink made with equal parts of lager and cider. Snakebite in the United Kingdom may be served with a dash of blackcurrant cordial, referred to as a snakebite and black. Stout may be used instead of lager in the United States.','https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Snakebite_alcoholic_beverage.jpg/220px-Snakebite_alcoholic_beverage.jpg','2018-07-22 18:50:13.524','2018-07-22 18:50:13.524',28,true,4,'beer','London',9,'Pint Glass',4.19)
;